'use strict';

var fs = require('fs');
var path = require('path');

var cachedThemes = null;

/**
 * Scan source/css/_partial/*.styl for files containing the metadata comment:
 *   /* @theme <display-name> <data-theme-value> *​/
 * Returns an array of { name, displayName, dataTheme } objects.
 */
function discoverThemes(hexo) {
    if (cachedThemes) return cachedThemes;

    var partialDir = path.join(hexo.theme_dir, 'source', 'css', '_partial');
    var themes = [];

    if (!fs.existsSync(partialDir)) {
        cachedThemes = themes;
        return themes;
    }

    var files = fs.readdirSync(partialDir);
    files.forEach(function(filename) {
        if (path.extname(filename) !== '.styl') return;

        var filePath = path.join(partialDir, filename);
        var content = fs.readFileSync(filePath, 'utf-8');

        var match = content.match(/\/\*\s*@theme\s+(.+?)\s+(\S+?)\s*\*\//);
        if (!match) return;

        themes.push({
            name:        path.basename(filename, '.styl'),
            displayName: match[1].trim(),
            dataTheme:   match[2].trim()
        });
    });

    // Sort: theme with dataTheme === 'dark' serves as the default (first).
    themes.sort(function(a, b) {
        if (a.dataTheme === 'dark') return -1;
        if (b.dataTheme === 'dark') return 1;
        return a.name.localeCompare(b.name);
    });

    cachedThemes = themes;
    return themes;
}

/**
 * Write source/css/_partial/_themes.styl with @import lines for every theme.
 */
function writeThemesStyl(hexo, themes) {
    var outputPath = path.join(hexo.theme_dir, 'source', 'css', '_partial', '_themes.styl');
    var lines = ['/* Auto-generated by scripts/theme-loader.js -- DO NOT EDIT */', ''];

    themes.forEach(function(t) {
        lines.push('@import "' + t.name + '"');
    });

    lines.push('');
    fs.writeFileSync(outputPath, lines.join('\n'), 'utf-8');
}

// Write _themes.styl once at script load so it exists before the first build cycle.
(function init() {
    var themes = discoverThemes(hexo);
    writeThemesStyl(hexo, themes);
})();

// Re-generate _themes.styl before every generation cycle (handles hexo generate and hexo server).
hexo.on('generateBefore', function() {
    cachedThemes = null;
    var themes = discoverThemes(hexo);
    writeThemesStyl(hexo, themes);
});

// Helper: returns the full theme list for template loops.
hexo.extend.helper.register('get_theme_list', function() {
    return discoverThemes(hexo);
});

// Helper: returns the anti-flicker IIFE as a raw JS string for meta.ejs.
hexo.extend.helper.register('anti_flicker_script', function() {
    var themes = discoverThemes(hexo);

    if (themes.length === 0) {
        return '(function(){var t=localStorage.getItem("theme")||"tech",d="dark";'
            + 'document.documentElement.setAttribute("data-theme",d)})();';
    }

    var first = themes[0];
    var lines = [];
    lines.push('(function(){');
    lines.push('var t=localStorage.getItem("theme")||"' + first.name + '";');
    lines.push('var d="' + first.dataTheme + '";');

    for (var i = 1; i < themes.length; i++) {
        var keyword = (i === 1) ? 'if' : 'else if';
        lines.push(keyword + '(t==="' + themes[i].name + '")d="' + themes[i].dataTheme + '";');
    }

    lines.push('document.documentElement.setAttribute("data-theme",d)})();');
    return lines.join('');
});
